### PR TITLE
Update theme.css

### PR DESCRIPTION
**Pull request by Shivangi1217**
Please see if it is alright.
I will make required changes based on your recommendation.

### CODE REVIEW

**Comment by Shivangi1217** [comment]
Sir can I contribute more on this project?
Actually I am having my mid semester exams going on.
After that I want to contribute.

**Comment by abel-otegbola** [comment]
Sure. Anytime. 

And don't forget to star the project. Thanks for the contributions

**Comment by Shivangi1217** [comment]
Ok Sir
Thanks

**Comment by abel-otegbola** [comment]
You still haven't started the repo

**Comment by Shivangi1217** [comment]
Sir done

**Comment by Shivangi1217** [comment]
Sir please accept my PR's .
I have lost my previous account through which I made contribution to your
fabulous clock project (the 3D one).

**Pull request merged**
