### PR TITLE
Move clock when page scroll is used

### PR DESCRIPTION
**Pull request by isinek**

### CODE REVIEW

**Comment by abel-otegbola** [comment]
Hi @isinek  please star the repo. Once you do that. I'll merge your pull request. Thanks

**Comment by abel-otegbola** [comment]
Also. I discovered the fixed positioning will distort the position of the floating balls for Glassmorphism. Why not add a theme, something amazing like an alien watch, apple watch etc

**Comment by isinek** [comment]
Hi, I've already star your repo.
I'll for sure also add a theme later, but this seemed useful since clock is not always visible.
There's also a option to have a scroll for theme list, then whole page will be visible without scrolling.
What do you think?

**Review by abel-otegbola — CHANGES_REQUESTED** [review]
A change of code that will break some parts of the projects can't be accepted. If you can create the theme instead it will be accepted.

**Pull request closed without merging**
