### PR TITLE
New

### PR DESCRIPTION
**Pull request by shiva1217**
Added apple theme

### CODE REVIEW

**Comment by shiva1217** [comment]
Added apple theme to the clock.
Please accept it 🙏

**Comment by shiva1217** [comment]
Sir please provide hacktoberfest label.

**Comment by shiva1217** [comment]
Sir is there any other repos of yours where I can contribute in hacktoberfest?

**Comment by abel-otegbola** [comment]
No. To give enough time to maintenance of this repo. I've decided not to open contribution to others

**Pull request merged**
