### PR TITLE
Update theme.css

### PR DESCRIPTION
**Pull request by shiva1217**

### CODE REVIEW

**Comment by abel-otegbola** [comment]
You should send only one pull request having the contributions in index.html and theme.css

**Comment by abel-otegbola** [comment]
I really appreciate that you want to contribute but please follow the rules stated on the repo readme.
Thanks

**Comment by shiva1217** [comment]
Sir there are some issues with me that's why I am not able to add both files together.
Can I add two files from two different usernames??

**Comment by abel-otegbola** [comment]
Making contribution shouldn't be an issue. You can even do so right here on GitHub. 

1. Fork the repo
2. In your fork, create a new branch
3. Add your changes to the index.html and commit changes
4. Add your changes to theme.css and commit changes
5. Pull request using the new branch.

**Pull request closed without merging**
