### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by Shivangi1217**
Changed display to inline

### CODE REVIEW

**Comment by Shivangi1217** [comment]
Please review it.
If not useful then I myself will delete it.

**Comment by Shivangi1217** [comment]
Please don't label spam .

**Comment by abel-otegbola** [comment]
Hi @Shivangi1217 sorry I'm just responding to your pull request.

I'm glad that you didn't spam the repo and that you want to contribute to the project. 

The changes you want make isn't really going to improve the project but if you can create a theme in the project, that will be appreciated. If you need guidelines to create a theme, let me know.

**Comment by Shivangi1217** [comment]
Oh sorry to trouble you.

I really want to contribute to your project.
It will be very kind if you provide guideline.

**Comment by abel-otegbola** [comment]
1 Open up index.html, Add your own theme to the lists.
      - Add your data-theme name
      - Use fontawesome icon name to add your icon
Screenshot_20221015-100813

2 Open the theme.css and Style your theme using the data-theme you set. Forexample
``` 
article[data-theme="wooden"] .clock {
   // Your styles
}
```

3 Optional. You can also style the dark version of your theme at the darkmode.css using  .dark

Looking forward to the awesome theme you will create.

**Pull request closed without merging**
